import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Provider from './providers';
import { Toaster } from 'react-hot-toast';

const christFont = localFont({
  src: './fonts/NightmareBeforeChristmas.woff',
  variable: '--font-christ',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${christFont.variable}`}>
        <Toaster position="top-center" toastOptions={{ duration: 5000 }} />
        <Provider>
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
